config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :products do
      resources :variants do
        resources :variant_properties
      end
    end
  end
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/property_decorator.rb
module Spree
  Property.class_eval do
    has_many :variant_properties, dependent: :delete_all
    has_many :variants, through: :variant_properties
  end
end

app/models/spree/variant_decorator.rb
module Spree
  Variant.class_eval do
    has_many :variant_properties, dependent: :destroy
    has_many :properties, through: :variant_properties

    accepts_nested_attributes_for :variant_properties, allow_destroy: true, reject_if: lambda { |vp| vp[:property_name].blank? }

    def property(property_name)
      return nil unless prop = properties.find_by(name: property_name)
      variant_properties.find_by(property: prop).try(:value)
    end

    def set_property(property_name, property_value)
      ActiveRecord::Base.transaction do
        property = Spree::Property.where(name: property_name).first_or_create!(presentation: property_name)
        variant_property = Spree::VariantProperty.where(variant: self, property: property).first_or_initialize
        variant_property.value = property_value
        variant_property.save!
      end
    end
  end
end

app/models/spree/variant_property.rb
module Spree
  class VariantProperty < ActiveRecord::Base
    belongs_to :variant, class_name: 'Spree::Variant'
    belongs_to :property, class_name: 'Spree::Property'

    validates :property, presence: true

    def property_name
      property.name if property
    end

    def property_name=(name)
      unless name.blank?
        unless property = Spree::Property.find_by(name: name)
          property = Spree::Property.create(name: name, presentation: name)
        end
        self.property = property
      end
    end
  end
end

app/controllers/spree/admin/variant_properties_controller.rb
module Spree
  module Admin
    class VariantPropertiesController < ResourceController
      belongs_to 'spree/variant', :find_by => :id
      before_filter :find_product
      before_filter :find_properties
      before_filter :setup_property, :only => [:index]

      respond_to :json

      private
        def find_product
          @product = Spree::Product.find_by(slug: params[:product_id])
        end

        def find_properties
          @properties = Spree::Property.pluck(:name)
        end

        def setup_property
          @variant.variant_properties.build
        end

        def location_after_destroy
          admin_product_variant_variant_properties_url(@product, @variant)
        end

        def location_after_save
          admin_product_variant_variant_properties_url(@product, @variant)
        end
    end
  end
end

app/controllers/spree/admin/variants_controller_decorator.rb
module Spree
  Admin::VariantsController.class_eval do
    update.before :update_before

    protected
      def update_before
        return unless params[:clear_variant_properties]
        params[:variant] ||= {}
      end
  end
end

app/controllers/spree/products_controller_decorator.rb
Spree::ProductsController.class_eval do
  before_filter :load_product, only: [:show, :show_variant_properties]

  respond_to :html, except: :show_variant_properties

  respond_to :js, only: :show_variant_properties
 
  def show
    return unless @product

    @variants = @product.variants_including_master.active(current_currency).includes([:option_values, :images])
    @product_properties = @product.product_properties.includes(:property)


    @variant_properties = @product.variants.first.variant_properties if @product.variants.first

    referer = request.env['HTTP_REFERER']
    if referer
      begin
        referer_path = URI.parse(request.env['HTTP_REFERER']).path
        # Fix for #2249
      rescue URI::InvalidURIError
        # Do nothing
      else
        if referer_path && referer_path.match(/\/t\/(.*)/)
          @taxon = Spree::Taxon.find_by_slug($1)
        else
          @taxon = Spree::Product.find_by_slug(params[:id]).taxons.first
        end
      end
    end
  end

  def show_variant_properties
    @product_properties = @product.product_properties.includes(:property)
    @variant_properties = @product.variants.find(params[:variant_id]).variant_properties
    respond_with @variant_properties
  end
end

app/views/spree/admin/variant_properties/_edit_variant_links.html.erb
<div class="form-buttons filter-actions actions" data-hook="buttons">
  <%= button Spree.t('actions.update'), 'icon-refresh' %>
  <span class="or"><%= Spree.t(:or) %></span>
  <%= button_link_to Spree.t('actions.cancel'), admin_product_variant_variant_properties_url(@product, @variant), :icon => 'icon-remove' %>
</div>

app/views/spree/admin/variant_properties/_variant_property_fields.html.erb
<tr class="variant_property fields" id="spree_<%= dom_id(f.object) %>" data-hook="variant_property">
  <td class="no-border">
    <span class="handle"></span>
    <%= f.hidden_field :id %>
  </td>
  <td class='property_name'>
    <%= f.text_field :property_name, :class => 'autocomplete' %>
  </td>
  <td class='value'>
    <%= f.text_field :value %>
  </td>
  <td class="actions">
    <% if f.object.persisted? %>
      <%= link_to_with_icon 'icon-trash', '', admin_product_variant_variant_property_url(@product, @variant, f.object), { class: 'no-text delete-resource', data: { :confirm => Spree.t(:are_you_sure), :action => 'remove' } } %>
    <% end %>
  </td>
</tr>

app/views/spree/admin/variant_properties/index.html.erb
<%= render 'spree/admin/shared/product_sub_menu' %>
<%= render 'spree/admin/shared/product_tabs', :current => 'Variant Properties' %>
<%= render 'spree/shared/error_messages', :target => @variant %>

<% content_for :page_actions do %>
  <ul class="tollbar inline-menu">
    <li>
      <%= link_to_add_fields 'ADD VARIANT PROPERTIES', 'tbody#variant_properties', :class => 'icon-plus button' %>
    </li>
  </ul>
<% end %>

<%= form_for @variant, :url => admin_product_variant_url(@product, @variant), :method => :put do |f| %>
  <fieldset class="no-border-top">
    <div class="add_variant_properties" data-hook="add_variant_properties"></div>

    <%= image_tag 'select2-spinner.gif', :plugin => 'spree', :style => 'display:none;', :id => 'busy_indicator' %>

    <table class="index sortable">
      <thead>
        <tr data-hook="variant_properties_header">
          <th colspan="2"><%= Spree.t(:property) %></th>
          <th><%= Spree.t(:value) %></th>
          <th class="actions"></th>
        </tr>
      </thead>
      <tbody id="variant_properties" data-hook>
        <%= f.fields_for :variant_properties do |vp_form| %>
          <%= render 'variant_property_fields', :f => vp_form %>
        <% end %>
      </tbody>
    </table>

    <%= render 'edit_variant_links' %>

    <%= hidden_field_tag 'clear_variant_properties', 'true' %>
  </fieldset>
<% end %>

<%= javascript_tag do -%>
  var properties = <%= raw(@properties.to_json) %>;
  $('#variant_properties').on('keydown', 'input.autocomplete', function() {
    already_auto_completed = $(this).is('ac_input');
    if (!already_auto_completed) {
      $(this).autocomplete({source: properties});
      $(this).focus();
    }
  });
<% end -%>

app/views/spree/products/show_variant_properties.js.erb
$("[data-hook='product_properties']").html("<%= escape_javascript(render :partial => 'spree/products/properties', :variant_properties => @variant_properties) %>")